# Generated by Django 5.0 on 2023-12-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(default='Unbekannt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_1000',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_480',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
