# Generated by Django 5.0 on 2023-12-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_video_genre_video_video_file_1000_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_1000',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_480',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_720',
        ),
    ]
